version: '3'
services:
  reddit_bot_1:
    image: reddit-bot:latest
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - PASSWORD=${PASSWORD}
      - USER_AGENT=YourBotName by /u/YourRedditUsername
      - SUBREDDIT=${SUBREDDIT}
      - KEYWORD=${KEYWORD}
      - API_KEY=${API_KEY}
    ports:
      - "80:80"
    # Add other service configuration as needed
