name: Run Docker Compose Every Hour

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest

    env:
      # Map secrets to environment variables
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
      SUBREDDIT: 'WhitePeopleTwitter'
      KEYWORD: 'Trump'
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t reddit-bot:latest -f Dockerfile .
      
      - name: Check for docker-compose.yml
        run: |
          ls -al

      - name: Run Docker Compose
        run: |
          docker compose up -d

      - name: Show Container Logs
        run: |
          docker logs reddit_bot_1